---
development:
  cloud_name: the-pivot
  api_key: '883859965577646'
  api_secret: GHTvYaInUzHrwqvtCyQbHsd2KIA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: the-pivot
  api_key: '883859965577646'
  api_secret: GHTvYaInUzHrwqvtCyQbHsd2KIA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: the-pivot
  api_key: '883859965577646'
  api_secret: GHTvYaInUzHrwqvtCyQbHsd2KIA
  enhance_image_tag: true
  static_image_support: false
